title: My Bonsai
description: "A jekyll template for semantically inclined digital gardeners."
url: "https://my-bonsai.com"
# baseurl: ""

# GitHub Pages: use remote_theme instead of theme
remote_theme: manunamz/jekyll-bonsai

include:
  - "_pages"
exclude:
  - "README.md"

collections:
  books:
    output: true
  entries:
    output: true
  states:
    output: true
    order:
      - tags.md
      - sprout.md
      - bud.md
      - bamboo.md
      - bloom.md
      - berry.md
      - fruit.md
      - melon.md
      - seed.md
      - tea.md
      - pot-bamboo.md

# frontmatter defaults
defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      permalink: "/post/:title/"
  - scope:
      type: "books"
    values:
      layout: "book"
      permalink: "/book/:path/"
  - scope:
      type: "entries"
    values:
      layout: "entry"
      permalink: "/entry/:path/"
  - scope:
      type: "states"
    values:
      layout: "state"
      permalink: "/stat/:path/"

# required for remote_theme on GitHub Pages
plugins:
  - jekyll-remote-theme

# Google Analytics (ip is anonymized by default)
ga_tracking: UA-190413040-3

namespaces:
  exclude:
    - "books"
    - "pages"
    - "posts"
    - "states"

bonsai:
  default_theme: "light"
  nav:
    type: "graph"
    graph:
      type: "tree"
  home:
    notable:
      enabled: false
    recent:
      enabled: true
      cap: 3

social:
  connect:
    enabled: false
  share:
    enabled: true
    type:
      - "email"
      - "facebook"
      - "linkedin"
      - "twitter"
